use beskar_core::drivers::keyboard::KeyCode;

/// Scancode to KeyCode mapping for PS/2 Set 1.
pub struct Ps2Set1Keycodes;

impl Ps2Set1Keycodes {
    #[must_use]
    #[expect(clippy::too_many_lines, reason = "Mapping tables are inherently long")]
    pub fn map(extended: bool, scancode: u8) -> Option<KeyCode> {
        let keycode = match (extended, scancode) {
            (false, 0x01) => Some(KeyCode::Escape),

            (false, 0x1E) => Some(KeyCode::A),
            (false, 0x30) => Some(KeyCode::B),
            (false, 0x2E) => Some(KeyCode::C),
            (false, 0x20) => Some(KeyCode::D),
            (false, 0x12) => Some(KeyCode::E),
            (false, 0x21) => Some(KeyCode::F),
            (false, 0x22) => Some(KeyCode::G),
            (false, 0x23) => Some(KeyCode::H),
            (false, 0x17) => Some(KeyCode::I),
            (false, 0x24) => Some(KeyCode::J),
            (false, 0x25) => Some(KeyCode::K),
            (false, 0x26) => Some(KeyCode::L),
            (false, 0x32) => Some(KeyCode::M),
            (false, 0x31) => Some(KeyCode::N),
            (false, 0x18) => Some(KeyCode::O),
            (false, 0x19) => Some(KeyCode::P),
            (false, 0x10) => Some(KeyCode::Q),
            (false, 0x13) => Some(KeyCode::R),
            (false, 0x1F) => Some(KeyCode::S),
            (false, 0x14) => Some(KeyCode::T),
            (false, 0x16) => Some(KeyCode::U),
            (false, 0x2F) => Some(KeyCode::V),
            (false, 0x11) => Some(KeyCode::W),
            (false, 0x2D) => Some(KeyCode::X),
            (false, 0x15) => Some(KeyCode::Y),
            (false, 0x2C) => Some(KeyCode::Z),

            (false, 0x0B) => Some(KeyCode::Num0),
            (false, 0x02) => Some(KeyCode::Num1),
            (false, 0x03) => Some(KeyCode::Num2),
            (false, 0x04) => Some(KeyCode::Num3),
            (false, 0x05) => Some(KeyCode::Num4),
            (false, 0x06) => Some(KeyCode::Num5),
            (false, 0x07) => Some(KeyCode::Num6),
            (false, 0x08) => Some(KeyCode::Num7),
            (false, 0x09) => Some(KeyCode::Num8),
            (false, 0x0A) => Some(KeyCode::Num9),

            (false, 0x0C) => Some(KeyCode::Minus),
            (false, 0x0D) => Some(KeyCode::Equal),
            (false, 0x1A) => Some(KeyCode::LeftBracket),
            (false, 0x1B) => Some(KeyCode::RightBracket),
            (false, 0x2B) => Some(KeyCode::Backslash),
            (false, 0x27) => Some(KeyCode::Semicolon),
            (false, 0x28) => Some(KeyCode::Apostrophe),
            (false, 0x29) => Some(KeyCode::Tilde),
            (false, 0x33) => Some(KeyCode::Comma),
            (false, 0x34) => Some(KeyCode::Dot),
            (false, 0x35) => Some(KeyCode::Slash),

            (false, 0x1C) => Some(KeyCode::Enter),
            (false, 0x39) => Some(KeyCode::Space),
            (false, 0x0E) => Some(KeyCode::Backspace),
            (false, 0x0F) => Some(KeyCode::Tab),
            (false, 0x3A) => Some(KeyCode::CapsLock),
            (false, 0x2A) => Some(KeyCode::ShiftLeft),
            (false, 0x36) => Some(KeyCode::ShiftRight),
            (false, 0x1D) => Some(KeyCode::CtrlLeft),
            (false, 0x38) => Some(KeyCode::AltLeft),

            (false, 0x3B) => Some(KeyCode::F1),
            (false, 0x3C) => Some(KeyCode::F2),
            (false, 0x3D) => Some(KeyCode::F3),
            (false, 0x3E) => Some(KeyCode::F4),
            (false, 0x3F) => Some(KeyCode::F5),
            (false, 0x40) => Some(KeyCode::F6),
            (false, 0x41) => Some(KeyCode::F7),
            (false, 0x42) => Some(KeyCode::F8),
            (false, 0x43) => Some(KeyCode::F9),
            (false, 0x44) => Some(KeyCode::F10),
            (false, 0x45) => Some(KeyCode::NumLock),
            (false, 0x46) => Some(KeyCode::ScrollLock),
            (false, 0x57) => Some(KeyCode::F11),
            (false, 0x58) => Some(KeyCode::F12),

            (false, 0x52) => Some(KeyCode::Numpad0),
            (false, 0x4F) => Some(KeyCode::Numpad1),
            (false, 0x50) => Some(KeyCode::Numpad2),
            (false, 0x51) => Some(KeyCode::Numpad3),
            (false, 0x4B) => Some(KeyCode::Numpad4),
            (false, 0x4C) => Some(KeyCode::Numpad5),
            (false, 0x4D) => Some(KeyCode::Numpad6),
            (false, 0x47) => Some(KeyCode::Numpad7),
            (false, 0x48) => Some(KeyCode::Numpad8),
            (false, 0x49) => Some(KeyCode::Numpad9),
            (false, 0x4E) => Some(KeyCode::NumpadAdd),
            (false, 0x4A) => Some(KeyCode::NumpadSub),
            (false, 0x37) => Some(KeyCode::NumpadMul),
            (false, 0x53) => Some(KeyCode::NumpadDot),

            (true, 0x1C) => Some(KeyCode::NumpadEnter),
            (true, 0x35) => Some(KeyCode::NumpadDiv),

            (true, 0x1D) => Some(KeyCode::CtrlRight),
            (true, 0x38) => Some(KeyCode::AltRight),

            (true, 0x47) => Some(KeyCode::Home),
            (true, 0x49) => Some(KeyCode::PageUp),
            (true, 0x4F) => Some(KeyCode::End),
            (true, 0x51) => Some(KeyCode::PageDown),
            (true, 0x52) => Some(KeyCode::Insert),
            (true, 0x53) => Some(KeyCode::Delete),

            (true, 0x48) => Some(KeyCode::ArrowUp),
            (true, 0x50) => Some(KeyCode::ArrowDown),
            (true, 0x4B) => Some(KeyCode::ArrowLeft),
            (true, 0x4D) => Some(KeyCode::ArrowRight),

            (true, 0x5B) => Some(KeyCode::WindowsLeft),
            (true, 0x5C) => Some(KeyCode::WindowsRight),
            (true, 0x5D) => Some(KeyCode::Menu),

            _ => None,
        }?;

        Some(keycode)
    }
}

/// Scancode to KeyCode mapping for PS/2 Set 2 and Set 3.
pub struct Ps2Set2Keycodes;

impl Ps2Set2Keycodes {
    #[must_use]
    #[expect(clippy::too_many_lines, reason = "Mapping tables are inherently long")]
    pub fn map(extended: bool, scancode: u8) -> Option<KeyCode> {
        let keycode = match (extended, scancode) {
            (false, 0x01) => Some(KeyCode::F9),
            (false, 0x03) => Some(KeyCode::F5),
            (false, 0x04) => Some(KeyCode::F3),
            (false, 0x05) => Some(KeyCode::F1),
            (false, 0x06) => Some(KeyCode::F2),
            (false, 0x07) => Some(KeyCode::F12),
            (false, 0x09) => Some(KeyCode::F10),
            (false, 0x0A) => Some(KeyCode::F8),
            (false, 0x0B) => Some(KeyCode::F6),
            (false, 0x0C) => Some(KeyCode::F4),
            (false, 0x0D) => Some(KeyCode::Tab),
            (false, 0x0E) => Some(KeyCode::Tilde),
            (false, 0x11) => Some(KeyCode::AltLeft),
            (false, 0x12) => Some(KeyCode::ShiftLeft),
            (false, 0x14) => Some(KeyCode::CtrlLeft),
            (false, 0x15) => Some(KeyCode::Q),
            (false, 0x16) => Some(KeyCode::Num1),
            (false, 0x1A) => Some(KeyCode::Z),
            (false, 0x1B) => Some(KeyCode::S),
            (false, 0x1C) => Some(KeyCode::A),
            (false, 0x1D) => Some(KeyCode::W),
            (false, 0x1E) => Some(KeyCode::Num2),
            (false, 0x21) => Some(KeyCode::C),
            (false, 0x22) => Some(KeyCode::X),
            (false, 0x23) => Some(KeyCode::D),
            (false, 0x24) => Some(KeyCode::E),
            (false, 0x25) => Some(KeyCode::Num4),
            (false, 0x26) => Some(KeyCode::Num3),
            (false, 0x29) => Some(KeyCode::Space),
            (false, 0x2A) => Some(KeyCode::V),
            (false, 0x2B) => Some(KeyCode::F),
            (false, 0x2C) => Some(KeyCode::T),
            (false, 0x2D) => Some(KeyCode::R),
            (false, 0x2E) => Some(KeyCode::Num5),
            (false, 0x31) => Some(KeyCode::N),
            (false, 0x32) => Some(KeyCode::B),
            (false, 0x33) => Some(KeyCode::H),
            (false, 0x34) => Some(KeyCode::G),
            (false, 0x35) => Some(KeyCode::Y),
            (false, 0x36) => Some(KeyCode::Num6),
            (false, 0x3A) => Some(KeyCode::M),
            (false, 0x3B) => Some(KeyCode::J),
            (false, 0x3C) => Some(KeyCode::U),
            (false, 0x3D) => Some(KeyCode::Num7),
            (false, 0x3E) => Some(KeyCode::Num8),
            (false, 0x41) => Some(KeyCode::Comma),
            (false, 0x42) => Some(KeyCode::K),
            (false, 0x43) => Some(KeyCode::I),
            (false, 0x44) => Some(KeyCode::O),
            (false, 0x45) => Some(KeyCode::Num0),
            (false, 0x46) => Some(KeyCode::Num9),
            (false, 0x49) => Some(KeyCode::Dot),
            (false, 0x4A) => Some(KeyCode::Slash),
            (false, 0x4B) => Some(KeyCode::L),
            (false, 0x4C) => Some(KeyCode::Semicolon),
            (false, 0x4D) => Some(KeyCode::P),
            (false, 0x4E) => Some(KeyCode::Minus),
            (false, 0x52) => Some(KeyCode::Apostrophe),
            (false, 0x54) => Some(KeyCode::LeftBracket),
            (false, 0x55) => Some(KeyCode::Equal),
            (false, 0x58) => Some(KeyCode::CapsLock),
            (false, 0x59) => Some(KeyCode::ShiftRight),
            (false, 0x5A) => Some(KeyCode::Enter),
            (false, 0x5B) => Some(KeyCode::RightBracket),
            (false, 0x5D) => Some(KeyCode::Backslash),
            (false, 0x66) => Some(KeyCode::Backspace),
            (false, 0x69) => Some(KeyCode::Numpad1),
            (false, 0x6B) => Some(KeyCode::Numpad4),
            (false, 0x6C) => Some(KeyCode::Numpad7),
            (false, 0x70) => Some(KeyCode::Numpad0),
            (false, 0x71) => Some(KeyCode::NumpadDot),
            (false, 0x72) => Some(KeyCode::Numpad2),
            (false, 0x73) => Some(KeyCode::Numpad5),
            (false, 0x74) => Some(KeyCode::Numpad6),
            (false, 0x75) => Some(KeyCode::Numpad8),
            (false, 0x76) => Some(KeyCode::Escape),
            (false, 0x77) => Some(KeyCode::NumLock),
            (false, 0x78) => Some(KeyCode::F11),
            (false, 0x79) => Some(KeyCode::NumpadAdd),
            (false, 0x7A) => Some(KeyCode::Numpad3),
            (false, 0x7B) => Some(KeyCode::NumpadSub),
            (false, 0x7C) => Some(KeyCode::NumpadMul),
            (false, 0x7D) => Some(KeyCode::Numpad9),
            (false, 0x7E) => Some(KeyCode::ScrollLock),
            (false, 0x83) => Some(KeyCode::F7),

            (true, 0x11) => Some(KeyCode::AltRight),
            (true, 0x14) => Some(KeyCode::CtrlRight),
            (true, 0x1F) => Some(KeyCode::WindowsLeft),
            (true, 0x27) => Some(KeyCode::WindowsRight),
            (true, 0x2F) => Some(KeyCode::Menu),
            (true, 0x4A) => Some(KeyCode::NumpadDiv),
            (true, 0x5A) => Some(KeyCode::NumpadEnter),
            (true, 0x69) => Some(KeyCode::End),
            (true, 0x6B) => Some(KeyCode::ArrowLeft),
            (true, 0x6C) => Some(KeyCode::Home),
            (true, 0x70) => Some(KeyCode::Insert),
            (true, 0x71) => Some(KeyCode::Delete),
            (true, 0x72) => Some(KeyCode::ArrowDown),
            (true, 0x74) => Some(KeyCode::ArrowRight),
            (true, 0x75) => Some(KeyCode::ArrowUp),
            (true, 0x7A) => Some(KeyCode::PageDown),
            (true, 0x7D) => Some(KeyCode::PageUp),

            _ => None,
        }?;

        Some(keycode)
    }
}
