[package]
name = "pci"
version = "0.1.0"
edition = "2024"

[dependencies]
acpi = { path = "../acpi" }
beskar-core = { workspace = true }
beskar-hal = { workspace = true }
driver-api = { path = "../../driver-api" }
hyperdrive = { workspace = true }
