[package]
name = "beskar-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
beskar-core = { workspace = true }
hyperdrive = { workspace = true }
linked_list_allocator = { version = "0.10.5", default-features = false }
