name: BeskarOS light CI

on:
  push:
    branches: ["dev","main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-check:
    name: Build and check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-unknown-none, x86_64-unknown-uefi
          components: clippy, llvm-tools-preview, rust-src

      - name: Build
        run: cargo build

      - name: Run tests
        run: |
          cargo test --package hyperdrive
          cargo test --package beskar-core

      - name: Run Clippy
        run: cargo clippy
