name: CI

# TODO: Different CI for dev and main branches
on:
  push:
    branches: ["main","dev"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-check:
    name: Build and check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-unknown-none, x86_64-unknown-uefi
          components: rustfmt, clippy, llvm-tools-preview, rust-src, miri

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --package hyperdrive

      # The project isn't advanced enough to have clippy fail
      # on warnings over all the code.
      - name: Run Clippy
        run: |
          cargo clippy --package hyperdrive -- -D warnings
          cargo clippy

      - name: Run Miri
        run: cargo miri test --package hyperdrive --lib

      - name: Run Rustfmt
        run: cargo fmt --verbose --all -- --check
